### ISSUE TITLE
Pep should die if contextbroker is not running

### ISSUE THREAD

**Issue by mcarracedo** [telefonicaid/fiware-pep-steelskin#223]
In the event of one contextbroker is not running, the corresponding PEP should die. This way the nginx will forward the requests to other active PEP-CB pair.

**Comment by fgalan** [comment]
Is this bug needed to be fixed for IoTP v2.0?

**Comment by dmoranj** [comment]
This is not a bug, as it was the expected functionality in the first place. As an improvement, we are creating a flag that lets the user configure whether he wants the PEP Proxy to stop on redirect error or return a 501 Code.

**Comment by dmoranj** [comment]
Fixed in #225
