### ISSUE TITLE
COMPONENT_NAME is not used to overwrite config.componentName 

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-pep-steelskin#226]
When `COMPONENT_NAME` environment variable is defined this is not used to overwrite `config.componentName` and it is really taken from `config.js` to compose FRN making a misconfiguration between middleware loaded and used into the FRN.

**Comment by fgalan** [comment]
Implemented in PR #227 (release/0.7.0) and PR #229 (develop)
