### ISSUE TITLE
Change RPM name to fiware-pep-steelskin

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-pep-steelskin#231]
Repo name was changed to fiware-pep-steelskin, but the RPM name is still fiware-orion-pep.

This issue is about chaning package name. Version number will not be affected.

**Effort: 1 man day**

**Comment by vgarciag** [comment]
The name of the package, at this moment,  is `pep-proxy` not `fiware-orion-pep`. I change the name of the package to `fiware-pep-steelskin`.

**Comment by fgalan** [comment]
Implemented in PR #234 (release/0.7.0) and PR #235 (develop).
