### ISSUE TITLE
PepProxy service doesn't work anymore

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#236]
Since the last changes in the init.d script, the pepProxy service doesn't work, due to an error finding the templates for the Access Control requests (as the executable is not invoked from the root folder of the project). This error must be resolved ASAP, as it means that any installation from the RPM simply does not work.

**Comment by fgalan** [comment]
Fixed in PR #237 (for release/0.7.0) and PR #238 (for defvelop).
