### ISSUE TITLE
Use environment variable to customize component name

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#240]
Currently, the only way to customize de component name protected by the PEP Proxy using configuration files is to declare it to use a different plugin. This may not be the right solution, specially for the cases of the generic REST plugin. A new environment variable `COMPONENT_NAME` should be created for this purpose.

**Comment by fgalan** [comment]
Fixed in PR #242 (develop) and PR #243 (release/0.7.0)
