### ISSUE TITLE
Rest plugin creates a FRN including the query parameters of the request

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#244]
When creating the FRN, the rest plugin uses the full URL of the resource, leaving the query parameters as well as the path. This causes some trouble with the XML parsing of the XACML request, and does not make much sense: only the path should be used instead.

**Comment by fgalan** [comment]
Fixed in PR #245 (develop) and PR #249 (release/0.7.0)
