### ISSUE TITLE
Service script init.d is broken by issue 240

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-pep-steelskin#246]
When new environment variable has been defined to solve issue https://github.com/telefonicaid/fiware-pep-steelskin/issues/240 this new environment variable has the same name that there were in init.d/pepProxy script and this makes than script cannot start service. A new name for the init.d script should be chosen to solve this.

**Comment by fgalan** [comment]
Fixed in PR #247 (release/0.7.0) and PR #248 (develop).
