### ISSUE TITLE
Creation of RPM fails due to a problem in the Changelog format

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#253]
The current changelog in `master` branch has the following format:
```
%changelog
=======
* Thu May 21 2015 Daniel Moran <daniel.moranjimenez@telefonica.com> 0.7.0
- Add capacity to start several instances of PEP Proxy using init.d script (#211)
- Add log debug statements for role extraction
- Fix error obtaining subservice ID from its name (208).
```
The `=======` characters are not expected by the parser, and thus, it brakes when trying to create the RPM. This problem seems to happen just in the `master` branch, as develop seems to be ok. Maybe we should check the release script that adds the CHANGES_NEXT_RELEASE contents to the changelog...

**Comment by fgalan** [comment]
Seems to be a leftover or a wrongly solved git conflict... :(

Maybe the best way of solving this is to do a fix-PR into master. However, be prepared by a develop-master conflict next time we frezee a release.

**Comment by dmoranj** [comment]
Fixed in develop.
