### ISSUE TITLE
Content-Type header in GET /v1/contextEntities/<id> returns 400 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-pep-steelskin#260]
The same header in orion (without pep) return 200
Without Content-Type pep returns 200
```
curl -i -X GET http://pep_orion_endpoint/v1/contextEntities/<device_id> -H "Accept: application/json" -H "Fiware-Service: todosincluidos" -H "Fiware-ServicePath: /iot" -H "x-auth-token: token" -H "Content-Type: application/json
```

**Comment by dmoranj** [comment]
This is the expected behavior, as an unexistent body is not a valid JSON file (if Context Broker accept that, that's a problem in the Context Broker rather than a bug in the PEP).
