### ISSUE TITLE
Distinguish NGSIv2 actions based on query parameters as well as URL

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#262]
Some NGSIv2 actions must be distinguished by reading some query paremeters. E.g.:
```
POST/v2/entities/<entityId>
```
and 
```
POST /v2/entities/<entityId>?op=append
```
The Orion plugin has to be modified to allow the same distinctions.

**Comment by fgalan** [comment]
Implemented in #261
