### ISSUE TITLE
Nginx error when transfer-encoding: chunked is specified

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#268]
When a GZipped transaction to the STH pass through an Nginx 1.0.x before entering the PEP Proxy, an error related to the decoding is returned to the client. It seems the error has to do with a duplicated "transfer-encoding: chunked" header or with the inability of the Nginx 1.0.x to forward HTTP/1.1 requests. The error has been tested with upper versions of Nginx and it's not reproducible.

**Comment by fgalan** [comment]
Fixed in PR in (develop) https://github.com/telefonicaid/fiware-pep-steelskin/pull/270. This was before [0.7.2](https://github.com/telefonicaid/fiware-pep-steelskin/releases/tag/0.7.2) releasing, to it should be included in that release.
