### ISSUE TITLE
Race condition causes requests that will never be responsed

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#269]
When two or more requests are received simultaneously by PEP proxy, at least one of them can be blocked (a request that is never sent a response).

There is no log in the PEP proxy that give a clue of this bug. The client will probably receive a timeout response from the NGINX or the load balancer in front of the PEP proxy. 
e.g. timeout response from nginx
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.0.15</center>
</body>
</html>
```

**Description of the problem in the code**
The race condition is coded in the implementation of access to the KeyStone, in the file [*]
the cache, in the file keystoneAuth.js
It is mainly caused in [this code line](https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/lib/services/keystoneAuth.js#L433) of the authenticate method
```
  authenticating = true;
  waitingRequests.removeAllListeners('token');
  waitingRequests.addListener('token', next);
```
When a request in progress is waiting the response of the "authenticate" request to the KeyStone, another request can run exacty the same code, because the authentication is in progress and "currentToken" is still "null". So the second request will remove all listeners of the common EventEmitter "waitingRequests" with the code "waitingRequests.removeAllListeners('token');". So the previous request will never receibe the "token" event and will never send the response to the client.

**Comment by fgalan** [comment]
Fixed in (develop) PR https://github.com/telefonicaid/fiware-pep-steelskin/pull/271. This was before [0.7.2](https://github.com/telefonicaid/fiware-pep-steelskin/releases/tag/0.7.2) releasing, to it should be included in that release.
