### ISSUE TITLE
Fiware service-path can contain more than one resource or entity

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#27]
Discussed in the following PR:

https://github.com/telefonicaid/fiware-orion-pep/pull/26

The PEP should modify the requests sent to the Access Control to reflect the fact of the service-path containing more than one resource or entity.

Effort: 2 man day

**Comment by dmoranj** [comment]
Not sure if this is the desirable behavior for IoT Platform or Fiware servicepath headers anymore. @fgalan Do you think this issue can be closed or is it expected in the future? (or maybe changing its value to nicetohave)

**Comment by fgalan** [comment]
The fact is that Orion accepts (in 0.19.0 and from some versions before) a queryContext with this kind of Fiware-ServicePath (similar for discoverContextAvailability, subscribeContext and other):

```
Fiware-ServicePath: /A, /A/B, /A/B/C/#
```

Thus, assuming that PEP only allows mono-element Fiware-Services implies "capping" Orion functionality in the securized API.

Not sure of to solve multi-element services path at PEP, but I think we shouldn't give up, so this issue should remained opened.

**Comment by dmoranj** [comment]
Seems to be duplicated in the #166 so this one is going to be closed.
