### ISSUE TITLE
Race condition causes "The token doesn't belong to the provided service"

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-pep-steelskin#272]
When two or more requests are received simultaneously by PEP proxy at least one of them could incorrectly fail due to a race condition in the code.

**The ouput log:**
```
lvl=ERROR | op=/v1/contextTypes?details=on&limit=1000&offset=0 | msg=Authentication rejected: the token does not match the service
lvl=ERROR | op=/v1/contextTypes?details=on&limit=1000&offset=0 | msg=[VALIDATION-GEN-003] Error connecting to Keystone authentication: TOKEN_DOES_NOT_MATCH_SERVICE: The provided token does not belong to the provided service.
lvl=ERROR | op=/v1/contextTypes?details=on&limit=1000&offset=0 | msg=Invalid token: null
```

**The response of the failed request:**
```
{ "name": "TOKEN_DOES_NOT_MATCH_SERVICE", "message": "The provided token does not belong to the provided service." }
```

**Description of the problem in the code**

The race condition is coded in the implementation of the cache, in the file cacheUtils.js
It is mainly caused [in this code line](https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/lib/services/cacheUtils.js#L84) of the cacheAndHold method
```
} else if (cache.updating[cacheType]) {
        cache.channel.on(cacheType, callback);
} else { 
```
When a request is in progress waiting the response of the "retrieveUser" request to the KeyStone, another request can run the cacheAndHold method. The variable *cache.updating.user" is still true and there isn't yet any value cached. The second request will run that line of code waiting to receive the "user" event (cacheType), when the event is received the "validateUserHeaders" will be executed, but that request won't have executed the "processValue" method that writes the "serviceId", "domainName" and "userId" in the request. Those properties are checked by the "validateUserHeaers".
It could be fixed making the event handler to call "processValue" when the updating is running. The race condition it is introduced by the access of the shared resource "cache".

**Comment by fgalan** [comment]
Merged (in develop) in PR https://github.com/telefonicaid/fiware-pep-steelskin/pull/273. This was before release/0.7.2 releasing, to it should be included in that release.
