### ISSUE TITLE
Failures on multiple simultaneous non-authenticated requests

### ISSUE THREAD

**Issue by giuliopaci** [telefonicaid/fiware-pep-steelskin#277]
Hi to all,
  I am experiencing issues when performing multiple unauthenticaded requests with steelskin.
I tried versions 0.7.0, 0.7.1 and 0.7.2 and they all behave the same.

My current setup is composed of orion, keystone and steelskin, without access control component.
Orion is configured for multitenancy and keystone is configured for multitenancy as well (using the SCIM extension). Everything is working as expected, except that if multiple requests  (>=2) are done with authentication failure, then steelskin will start truncating responses and dropping connections.

I am using okfi-sdk module (that I wrote) to interact with keystone and orion. Authentication is handled transparently by the module in this way:
Initially the query is performed without caring about authentication. If the request succeed, nothing more is done. If it fails due to an authentication error, authentication is tried and the request is performed again after authentication. If it fails for any other error, the request is tried again after an exponentially growing number of seconds.
After the first query, authentication token is reused, until it fails. Then authentication is performed as above.

The issue is that when trying multiple simultaneous initially unauthenticated queries, the clients start receiving connection errors and several retry attempts have to be performed, before the requests are able to succeed.

Attached are nodejs scripts showing the behaviour:
[bug.zip](https://github.com/telefonicaid/fiware-pep-steelskin/files/81165/bug.zip)

However the issue can be seen also by performing similar requests from multiple clients.

**Comment by giuliopaci** [comment]
Hi, any news about this issue?
This prevents this tool to be used in any scenario with untrusted users, as it is very easy for them to launch a Denial-Of-Service attack.
2-4 http calls with wrong authentication token are enough in my scenario to cause a DOS of some seconds.

**Comment by dmoranj** [comment]
We are working on solving it, thanks for your examples.

**Comment by dmoranj** [comment]
Fixed on #282
