### ISSUE TITLE
PEP: Race condition: Logs of diferent requests and transactions writing exactly the same correlatorId and transactionId

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-pep-steelskin#279]
There some parts of the code were the "node domain" used to keep the correlatorId and the transactionId is not used in a proper way. That is causing that the logs of some requests and transactions used the id of another transactions. So in that cases there is no way to match the logs with the correct request and transaction.
This scenario it is got when the PEP receive two o more simultaneous requests.
We have detected that problem in this line of code:
https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/lib/services/cacheUtils.js#L85
} else if (cache.updating[cacheType]) {
    cache.channel.on(cacheType, callback);
} else {
The request that is runing the method "cache.channel.on" is using a given "domain" with a given "corr" and "trans". But the "cacheType" event will be fired by the request that is resolving the request to the KeyStone. So the "callback" will write the logs using the wrong trans and corr id, the ones used by the other request.

https://jirapdi.tid.es/browse/DM-967

**Comment by manucarrace** [comment]
DANIEL MORAN JIMENEZ added a comment - 01/Dec/15 11:26 AM
Not easy to solve. This same problem will arise whenever the request encounters an Event Emitter. The solution may be the use of a decorator for the event listeners that capture the current domain and restablish it when the event listener is called (and to add that decorator to all on() methods in the code. This may impact a lots of features, so we should estimate carefully whether the benefit is worth the effort.

**Comment by fgalan** [comment]
Fixed (in develo) in PR #280
