### ISSUE TITLE
Weird behaviour in LOGLEVEL

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-pep-steelskin#374]
The log level setting has a weird behaviour when it is specified with upper cases (INFO, DEBUG...). This causes, for example, that the functionality to log the user operations not works.  In addition a not valid setting for this parameter is read as it were a valid value.

**Comment by AlvaroVega** [comment]
This bug was fixed in PR: https://github.com/telefonicaid/fiware-pep-steelskin/pull/373
Could you try it again?

**Comment by vgarciag** [comment]
Ok, I don't know that it was solved in that PR
