### ISSUE TITLE
Configure the operations that will be logged

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-pep-steelskin#375]
This is to configure the operations that will be logged into file. For example, using the Pep for Context Broker, may be that we can only log the operations to create/delete/update entities and subscriptions and not log context updates.

This is to avoid a huge rise of log file and manage what and not what to log.

**Comment by fgalan** [comment]
>  can only log the operations to create/delete/update entities and subscriptions and not log context updates

Not sure what do you mean... could you re-formulate the example based on verbs+URLs, please?

**Comment by vgarciag** [comment]
> Not sure what do you mean... could you re-formulate the example based on verbs+URLs, please?

Yes, this is an improvement to the functionality that logs operations in a file to specify what operations will be logged and what not be logged using a new parameter of configuration. IE:

`ACCESS_ACCOUNT_OPERATION=[entity_creation,entity_deletion,subscription_deletion]`

This only logs operations for entities creations/deletions and subscription deletions .
