### ISSUE TITLE
Log operations to file and loglevel

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-pep-steelskin#376]
Now the access operations are linked to a log level to work. This causes that if a log level is under the INFO no access operations  are logged. 

Access operations and service logs are different functionalities that not should be related with the log level.

**Comment by fgalan** [comment]
Maybe a new (and independent) lvl should be defined for it? e.g. AUDIT or ACCESS. Would Splunk deal with a new level?

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-pep-steelskin/pull/437

Should this issue be closed now that the PR is merged?
