### ISSUE TITLE
Improvements in /etc/init.d/pepProxy script

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-pep-steelskin#390]
Two improvements:

* In some cases (not sure... maybe related with pep upgrades), when restart is done not always the process is stoped. In this case, we get EADDDRINUSE and monit cannot manage properly the situation.
* In the case of serveral PEP processes running in the same machine, it is not clear which one to pick to be stoped:

```
$ ps -efa|grep pepProxy
pepproxy 22613 1 2 11:11 ? 00:00:00 node /opt/pepProxy/bin/pepProxy
pepproxy 22641 1 2 11:11 ? 00:00:00 node /opt/pepProxy/bin/pepProxy
```

it should be something like this:

```
pepproxy 22613 1 2 11:11 ? 00:00:00 node /opt/pepProxy/bin/pepProxy config.js <instance1>
pepproxy 22641 1 2 11:11 ? 00:00:00 node /opt/pepProxy/bin/pepProxy config.js <instance2>
```

**Comment by cesarjorgemartinez** [comment]
Fixed in PR: https://github.com/telefonicaid/fiware-pep-steelskin/pull/393
