### ISSUE TITLE
Correlator propagation is not working properly

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-pep-steelskin#468]
Testing in DEVEL environment with PEP and Orion, with PEP set to DEBUG loglevel (`curl -i -X PUT 'http://localhost:11211/admin/log?level=DEBUG'`). I sent the following request to PEP through PEP:

```
curl -H 'fiware-service: alcobendas' -H 'fiware-servicepath: /alumbrado' -H 'x-auth-token: ... ' localhost:1026/v2/entities
```

I get in PEP logs:

```
time=2021-11-17T12:38:19.938Z | lvl=DEBUG | corr=107f1453-9af4-4087-9cad-9b43a51425a8 | trans=107f1453-9af4-4087-9cad-9b43a51425a8 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=Extracting action from the URL "/v2/entities" | comp=PEPorion
time=2021-11-17T12:38:19.939Z | lvl=DEBUG | corr=107f1453-9af4-4087-9cad-9b43a51425a8 | trans=107f1453-9af4-4087-9cad-9b43a51425a8 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=Generated FRN:  | comp=PEPorion fiware:orion:alcobendas:/alumbrado:::
...
time=2021-11-17T12:38:20.512Z | lvl=DEBUG | corr=107f1453-9af4-4087-9cad-9b43a51425a8 | trans=107f1453-9af4-4087-9cad-9b43a51425a8 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=response-time: 574 statusCode: 200 | comp=PEPorion
```

I get in Orion logs:

```
time=2021-11-17T12:38:20.511Z | lvl=INFO | corr=3f11e4a6-47a3-11ec-8569-0242ac110018 | trans=1637123571-925-00000000305 | from=172.17.0.1 | srv=alcobendas | subsrv=/alumbrado | comp=Orion | op=logTracing.cpp[97]:logInfoRequestWithoutPayload | msg=Request received: GET /v2/entities, response code: 200
```

The corr= value doesn't match (in PEP is `107f1453-9af4-4087-9cad-9b43a51425a8` and in Orion is `3f11e4a6-47a3-11ec-8569-0242ac110018`).

Note that if the fiware-correlator header is provided in the request it works as expected. Request:

```
curl -H 'fiware-correlator: abcd1234' -H 'fiware-service: alcobendas' -H 'fiware-servicepath: /alumbrado' -H 'x-auth-token: ...' localhost:1026/v2/entities
```

PEP logs:

```
time=2021-11-17T12:39:29.503Z | lvl=DEBUG | corr=abcd1234 | trans=eee9222f-1104-4f9e-a130-d2a60db08314 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=Extracting action from the URL "/v2/entities" | comp=PEPorion
time=2021-11-17T12:39:29.503Z | lvl=DEBUG | corr=abcd1234 | trans=eee9222f-1104-4f9e-a130-d2a60db08314 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=Generated FRN:  | comp=PEPorion fiware:orion:alcobendas:/alumbrado:::
...
time=2021-11-17T12:39:30.010Z | lvl=DEBUG | corr=abcd1234 | trans=eee9222f-1104-4f9e-a130-d2a60db08314 | op=/v2/entities | from=n/a | srv=alcobendas | subsrv=/alumbrado | msg=response-time: 507 statusCode: 200 | comp=PEPorion
```

Orion logs:

```
time=2021-11-17T12:39:30.009Z | lvl=INFO | corr=abcd1234 | trans=1637123571-925-00000000306 | from=172.17.0.1 | srv=alcobendas | subsrv=/alumbrado | comp=Orion | op=logTracing.cpp[97]:logInfoRequestWithoutPayload | msg=Request received: GET /v2/entities, response code: 200
```

In this case both use `abcd1234`

**Comment by fgalan** [comment]
I have tested only the PEP-Orion case, but it could be happening with other components secured by PEP (Perseo FE, IOTAM, STH and Keypass).

**Comment by fgalan** [comment]
A possible solution is that PEP includes a `fiware-correlator`  header using the correlator generated by him in the case that header is not present in the origin request.

**Comment by AlvaroVega** [comment]
Correlator is handled by pep here:
https://github.com/telefonicaid/fiware-pep-steelskin/blob/1c78ae28832a223696c2b8e64fcd9c169f62beca/lib/middleware/domain.js#L91-L99

The behavior implemented is:
- if request has correlator then use it for response
- if no request has correlator then use a new one based on transaction id just created

**Comment by AlvaroVega** [comment]
BTW, pep is using 'Fiware-correlator' as name of header. Maybe other compontests are expecting that header in other cases (i.e. 'fiware-correlator', 'Fiware-Correlator'?

**Comment by fgalan** [comment]
> if no request has correlator then use a new one based on transaction id just created

PEP is typically the first element in the e2e chain, so it would make sense that if fiware-correlator is not provided by the client, then PEP choose the correlator an propagates with the fiware-correlator header

**Comment by fgalan** [comment]
> BTW, pep is using 'Fiware-correlator' as name of header. Maybe other compontests are expecting that header in other cases (i.e. 'fiware-correlator', 'Fiware-Correlator'?

HTTP headers names are case insensitive (see https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive/5259004). Thus is some component doesn't implement in that way, it is a bug that would need to be fixed. In the case of Orion, I have checked that it implements them in case insensitive way, so it's ok.

**Comment by fgalan** [comment]
Checked in DEVEL that after merging that PR it works as expected.
