### ISSUE TITLE
[macOS] Error when running local tests in macOS 12(Default port 5000 allocated by SO)

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/fiware-pep-steelskin#486]
When trying to run tests on macOS 12, every single test fails, giving the following error

```
Uncaught Error: listen EADDRINUSE: address already in use 0.0.0.0:5000
```

In order to check if there is a procces running in port `5000`, I ran:

```BASH
lsof -i:5000
COMMAND     PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ControlCe 46393 mpedraza   27u  IPv4 0xaf1c1b476bc2ff31      0t0  TCP *:commplex-main (LISTEN)
ControlCe 46393 mpedraza   28u  IPv6 0xaf1c1b47474f9eb9      0t0  TCP *:commplex-main (LISTEN)
````

It is confirmed, there is a system process that is running on port `5000`. After some research, I find out the process running on this port turns out to be an AirPlay server. You can deactivate it in System Preferences › Sharing, and unchecking AirPlay Receiver in order to release port `5000`.

Another alternative tu successfully run the tests is to edit `config.js` file changing port number at:
https://github.com/telefonicaid/fiware-pep-steelskin/blob/727b9ab84eed70971db2f7f61956a665739f7c7c/config.js#L88-L94 

I do not know if makes sense to change default port number to 5001 for instance

**Comment by mapedraza** [comment]
As discussed offline, no further action will be taken on this issue, so the issue now can be closed.

**Comment by fgalan** [comment]
The reason is that 5000 is widely extended in existing deployments, deployment scrripts, etc. Change this now would could cause problems with a very little gain.
