### ISSUE TITLE
Do not use domain context object: keep info in request

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-pep-steelskin#498]
Use request instead a domain object to store data about domainContext

Fast test:
Remove
/lib/fiware-pep-steelskin.js:233
/lib/fiware-pep-steelskin.js:317
lib/services/keystoneAuth.js:432
lib/services/cacheUtils.js:90

And store in request a dict named domain with domain context info.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-pep-steelskin/pull/508

**Comment by AlvaroVega** [comment]
PR 508 is related but not solves this issue

**Comment by fgalan** [comment]
PR #528
